### PR TITLE
Enable Google Java Format

### PR DESCRIPTION
**Pull request by sfc-gh-tzhang**
No functionality changes

### CODE REVIEW

**Review by sfc-gh-tjones — APPROVED** [review]

**Comment by sfc-gh-japatel** [comment]
Dont we also have to check in some xml file which will follow this format? Or this is just intellij settings? 
If only intellij settings, can you add it to readme file as well?

**Comment by sfc-gh-japatel** [comment]
> > Dont we also have to check in some xml file which will follow this format? Or this is just intellij settings?
> > If only intellij settings, can you add it to readme file as well?
> 
> It's just a IntelliJ plugin. What do you think we should add to the README?

If it is a plugin are we expected to install it? What if we dont install, is it going to mess up the files? 
I am just trying to understand what is the goal. (Apart from unified format, which I personally like, but may be having a merge gate regarding java formatter long term is the right approach)

**Comment by sfc-gh-tzhang** [comment]
> > > Dont we also have to check in some xml file which will follow this format? Or this is just intellij settings?
> > > If only intellij settings, can you add it to readme file as well?
> > 
> > 
> > It's just a IntelliJ plugin. What do you think we should add to the README?
> 
> If it is a plugin are we expected to install it? What if we dont install, is it going to mess up the files?
> I am just trying to understand what is the goal. (Apart from unified format, which I personally like, but may be having a merge gate regarding java formatter long term is the right approach)

Yes, you will need to install it, and we will need the merge gate in order to enforce it. Do you know who should I ask for enabling it for this repo?

**Comment by sfc-gh-japatel** [comment]
> > > Dont we also have to check in some xml file which will follow this format? Or this is just intellij settings?
> > > If only intellij settings, can you add it to readme file as well?
> > 
> > 
> > It's just a IntelliJ plugin. What do you think we should add to the README?
> 
> If it is a plugin are we expected to install it? What if we dont install, is it going to mess up the files?
> I am just trying to understand what is the goal. (Apart from unified format, which I personally like, but may be having a merge gate regarding java formatter long term is the right approach)

I think we are using spotless https://github.com/diffplug/spotless/tree/main/plugin-maven#google-java-format

**Comment by sfc-gh-japatel** [comment]
> > > > Dont we also have to check in some xml file which will follow this format? Or this is just intellij settings?
> > > > If only intellij settings, can you add it to readme file as well?
> > > 
> > > 
> > > It's just a IntelliJ plugin. What do you think we should add to the README?
> > 
> > 
> > If it is a plugin are we expected to install it? What if we dont install, is it going to mess up the files?
> > I am just trying to understand what is the goal. (Apart from unified format, which I personally like, but may be having a merge gate regarding java formatter long term is the right approach)
> 
> I think we are using spotless https://github.com/diffplug/spotless/tree/main/plugin-maven#google-java-format

JDBC does it using coveo:
https://github.com/snowflakedb/snowflake-jdbc/search?q=com.coveo
https://github.com/coveooss/fmt-maven-plugin

Using this will be easier to implement a merge gate.

**Comment by sfc-gh-tzhang** [comment]
I will go ahead and merge this change, in the meantime, I have asked in the engineering channel to see how to enable GoogleJavaFormat as part of the merge gate, let me know if you know how to do it :)

**Comment by sfc-gh-japatel** [comment]
> I will go ahead and merge this change, in the meantime, I have asked in the engineering channel to see how to enable GoogleJavaFormat as part of the merge gate, let me know if you know how to do it :)

https://github.com/snowflakedb/snowflake-ingest-java/pull/85#issuecomment-811491459
Adding a merge gate is fairly quick if we add a maven goal. 
1. https://docs.github.com/en/github/administering-a-repository/managing-a-branch-protection-rule
2. Adding a workflow similar to this one. https://github.com/snowflakedb/snowflake-ingest-java/blob/master/.github/workflows/End2EndTest.yml

**Pull request merged**
