### PR TITLE
[SNOW-693813] Remove exactly once methods calling into server

### PR DESCRIPTION
**Pull request by sfc-gh-rcheng**
Removed the following concepts and their corresponding requests/responses to the endpoints on the server side
- clientInfo
- clientStatus
- configureClient

KC calls to these endpoints were removed a while ago, @sfc-gh-japatel confirmed that there is no substantial traffic to these endpoints from non KC sources

### CODE REVIEW

**Comment by sfc-gh-tzhang** [comment]
> Removed the following concepts and their corresponding requests/responses to the endpoints on the server side

Is this a pure revert of the original commit? If no, could you please make sure that everything related is removed?

**Review by sfc-gh-tzhang — APPROVED** [review]
lgtm, thanks!

**Comment by sfc-gh-rcheng** [comment]
> Is this a pure revert of the original commit? If no, could you please make sure that everything related is removed?

Thanks for the tip! Found two unused calls I removed. 

I scanned this [jira](https://snowflakecomputing.atlassian.net/browse/SNOW-413991), found these prs https://github.com/snowflakedb/snowflake-ingest-java/pull/102, https://github.com/snowflakedb/snowflake-ingest-java/pull/105, and cross referenced any changes.

**Comment by illegalnumbers** [comment]
Is there a migration guide somewhere for users who consumed these?

**Pull request merged**
