### PR TITLE
V1.0.2-beta.4 release

### PR DESCRIPTION
**Pull request by sfc-gh-tzhang**
This release contains a few bug fixes and improvements for Snowpipe Streaming:

- [Bug Fix] Check max column length for Binary data type
- [Bug Fix] Fix ARRAY data type with String elements
- [Improvement] Support running IT tests as part of merge gate
- [Improvement] Update the InsertError response to include extra or missing column information

### CODE REVIEW

**Comment by sfc-gh-japatel** [comment]
Can you take a look at the failing tests in merge gate?

**Comment by sfc-gh-japatel** [comment]
@sfc-gh-jfan there is a failure in security snyk which I can access since I dont have a tile in okta. Can you take a look?

**Review by sfc-gh-japatel — APPROVED** [review]
lgtm! But I would wait for @sfc-gh-jfan to comment on a failed snyk merge gate.

**Comment by sfc-gh-jfan** [comment]
> @sfc-gh-jfan there is a failure in security snyk which I can access since I dont have a tile in okta. Can you take a look?

Hey, @sfc-gh-japatel  sure thing. just sent you via email

**Comment by sfc-gh-tzhang** [comment]
> > @sfc-gh-jfan there is a failure in security snyk which I can access since I dont have a tile in okta. Can you take a look?
> 
> Hey, @sfc-gh-japatel sure thing. just sent you via email

I don't think it's related to this PR, we had this issue and the dependency are from the Arrow library so there is nothing we can do

**Comment by sfc-gh-jfan** [comment]
> > > @sfc-gh-jfan there is a failure in security snyk which I can access since I dont have a tile in okta. Can you take a look?
> > 
> > 
> > Hey, @sfc-gh-japatel sure thing. just sent you via email
> 
> I don't think it's related to this PR, we had this issue and the dependency are from the Arrow library so there is nothing we can do

looks like it is introduced via snowflake:snowflake-ingest-sdk@1.0.2-beta.4 which is planned to upgrade in this PR.
could we talk to the team who is managing this dependency and fix it?

**Pull request merged**
