### PR TITLE
added latency to insser row method

### PR DESCRIPTION
**Pull request by sfc-gh-dshah**

### CODE REVIEW

**Review by sfc-gh-gdoci — CHANGES_REQUESTED** [review]
@sfc-gh-dshah Is this an unintentional change? It would make every `insertRow` call slower.

**Review by sfc-gh-tjones — CHANGES_REQUESTED** [review]
Echoing Gloria's comment - is this a mistake? Every insertRow call now takes one minute 😬

**Comment by sfc-gh-japatel** [comment]
Jumping in here: 
1. We dont plan to push this to master. 
2. We wanted to release a new slow version of Ingest SDK which mimics adding latency to insertRow. Not in public maven repo but in snowflake maven internal repo.  
3. We wanted to show case whether our benchmarking tests can catch that anomaly. 

(This version will only be released in internal maven repo with snapshot and new name to it)

@sfc-gh-dshah is not planning to push this, I dont even know if it was intentional to create a PR since she can release a new snapshot version from a branch and use that new release in benchmark tests. 


Feel free to ignore this!

**Comment by sfc-gh-japatel** [comment]
> Jumping in here:
> 
> 1. We dont plan to push this to master.
> 2. We wanted to release a new slow version of Ingest SDK which mimics adding latency to insertRow. Not in public maven repo but in snowflake maven internal repo.
> 3. We wanted to show case whether our benchmarking tests can catch that anomaly.
> 
> (This version will only be released in internal maven repo with snapshot and new name to it)
> 
> @sfc-gh-dshah is not planning to push this, I dont even know if it was intentional to create a PR since she can release a new snapshot version from a branch and use that new release in benchmark tests.
> 
> Feel free to ignore this!

Lets close this PR @sfc-gh-dshah !

**Pull request closed without merging**
