### PR TITLE
Remove guava dependency

### PR DESCRIPTION
**Pull request by sfc-gh-japatel**
Re: #100

### CODE REVIEW

**Review by sfc-gh-rramachandran — APPROVED** [review]
LGTM!

**Comment by ryanstrat** [comment]
Thanks for merging this, @sfc-gh-japatel. Can you ensure the updated version gets pulled into snowflakedb/spark-snowflake

**Comment by yuzhangyi** [comment]
@sfc-gh-rramachandran and @ryanstrat ,do you have plan to release new version spark-snowflake-sdk with removing the embed code and keep them as dependency (“com.google”, “javax”, “org.checkerframework” ) reference like before?

**Comment by sfc-gh-japatel** [comment]
I will schedule a release and let @sfc-gh-zli work on using the latest version in spark.

**Comment by yuzhangyi** [comment]
> I will schedule a release and let @sfc-gh-zli work on using the latest version in spark.

Thank you to help work on it, when it is ready in maven, we will upgrade our product to be newest version.

**Comment by yuzhangyi** [comment]
@sfc-gh-japatel and @sfc-gh-zli , this is kind ping, do we already have new version snowflake-sdk release with removing the embed code and keep them as dependency (“com.google”, “javax”, “org.checkerframework” ) reference like before? Thanks

**Comment by yuzhangyi** [comment]
@sfc-gh-japatel  and @sfc-gh-zli , this is kind ping, do we already have new version snowflake-sdk release with removing the embed code and keep them as dependency (“com.google”, “javax”, “org.checkerframework” ) reference like before? Thanks

**Comment by tom-s-powell** [comment]
Is there a plan for a release of this library that doesn't include guava or shades to avoid classpath conflicts?

**Pull request merged**
