### PR TITLE
NO-SNOW update Hadoop-commons 

### PR DESCRIPTION
**Pull request by sfc-gh-xhuang**
Update to 3.4.0

### CODE REVIEW

**Review by sfc-gh-tzhang — COMMENTED** [review]
Looks like the merge gating is failing as well

**Comment by sfc-gh-xhuang** [comment]
I thought it's failing because #756 needs to go in

**Comment by sfc-gh-lsembera** [comment]
> I thought it's failing because #756 needs to go in

@sfc-gh-xhuang PR #756 just adds testing that new dependencies with using multi-release JARs are working fine. Hadoop 3.3.x to 3.4.x will likely be a bigger change, do we need to do it now? Has Snyk found any issues with it?

**Comment by sfc-gh-xhuang** [comment]
@sfc-gh-lsembera I was hoping to upgrade it because of commons-configuration dependency. 
Snyk didn't call it out but another tool did

**Pull request closed without merging**
