### PR TITLE
V2.0.0 release

### PR DESCRIPTION
**Pull request by sfc-gh-tzhang**
Release 2.0.0, which will hopefully be the first stable release for internal GA

### CODE REVIEW

**Comment by sfc-gh-lsembera** [comment]
I thought we wanted to release it as 2.0.0 - to bump the major version due to the potential impact of shading. 
Please do not merge until https://github.com/snowflakedb/snowflake-ingest-java/pull/520, https://github.com/snowflakedb/snowflake-ingest-java/pull/519 and https://github.com/snowflakedb/snowflake-ingest-java/pull/521 are in. @sfc-gh-azagrebin do you want to merge anything else before the release?

//cc @sfc-gh-xhuang

**Comment by sfc-gh-xhuang** [comment]
Can we release as 1.1.5-beta? And release 2.0.0 as GA after the bake period?

**Comment by sfc-gh-lsembera** [comment]
@sfc-gh-xhuang I am afraid that nobody is going to upgrade to `1.1.5-beta`.

**Comment by sfc-gh-tzhang** [comment]
> I thought we wanted to release it as 2.0.0 - to bump the major version due to the potential impact of shading. Please do not merge until #520, #519 and #521 are in. @sfc-gh-azagrebin do you want to merge anything else before the release?
> 
> //cc @sfc-gh-xhuang

We can't wait for https://github.com/snowflakedb/snowflake-ingest-java/pull/521 since it will at least takes two weeks for the server side change to be stable, we can add it later since it's a low risk change and won't affect performance

**Review by sfc-gh-tjones — APPROVED** [review]

**Pull request merged**
