### PR TITLE
V1.0.2-beta.5 release

### PR DESCRIPTION
**Pull request by sfc-gh-tzhang**
This release contains a few bug fixes and improvements for Snowpipe Streaming:
- [Improvement] Improve and fix a few data type validation logic
- [Improvement] Add throttling logic on direct memory based on uploading queue size
- [Improvement] Add basic logic to support Parquet file format, this work is still in progress and we're still using Arrow
- [Improvement] Improve exception handling logic

### CODE REVIEW

**Comment by sfc-gh-japatel** [comment]
> Add basic support to support Parquet file format, work is still in progress
Have we migrated or we are still on arrow but this is just new code which is not kicked off?

**Comment by sfc-gh-tzhang** [comment]
> > Add basic support to support Parquet file format, work is still in progress
> > Have we migrated or we are still on arrow but this is just new code which is not kicked off?

`work is still in progress` basically means the work is not done and we're still using Arrow, any suggestion to make it more clear?

**Comment by sfc-gh-japatel** [comment]
> > > Add basic support to support Parquet file format, work is still in progress
> > > Have we migrated or we are still on arrow but this is just new code which is not kicked off?
> 
> `work is still in progress` basically means the work is not done and we're still using Arrow, any suggestion to make it more clear?

Sounds good, I would mention that `Arrow is still used but improvements added to switch to parquet. `

**Review by sfc-gh-japatel — APPROVED** [review]

**Comment by sfc-gh-tzhang** [comment]
@sfc-gh-jfan Any idea about the synk failure? I don't have permission to access the log

**Pull request merged**
