### PR TITLE
Adding a script to release unshaded version into S3 repo

### PR DESCRIPTION
**Pull request by sfc-gh-hqin**

### CODE REVIEW

**Comment by sfc-gh-japatel** [comment]
I see an unshaded version in maven, is this expected? https://repo1.maven.org/maven2/net/snowflake/snowflake-ingest-sdk/

**Comment by sfc-gh-tzhang** [comment]
@sfc-gh-japatel could you help taking a look at this PR when it's ready for review? Thanks!

**Review by sfc-gh-japatel — APPROVED** [review]
lgtm! 

- Can this be hooked up with normal release? So that everytime we release normal version, we have unshaded release as well

**Comment by sfc-gh-dwang** [comment]
> I see an unshaded version in maven, is this expected? https://repo1.maven.org/maven2/net/snowflake/snowflake-ingest-sdk/

yes, this was created last time

**Comment by sfc-gh-dwang** [comment]
> lgtm!
> 
> * Can this be hooked up with normal release? So that everytime we release normal version, we have unshaded release as well

release team will do that base on this PR

**Pull request merged**
