### PR TITLE
Release version 1.0.1-beta

### PR DESCRIPTION
**Pull request by sfc-gh-tzhang**
Release note:
1. Fix EP generation for a few data types
2. A few adjustments to be more conservative on memory consumption
3. Add more logging

### CODE REVIEW

**Review by sfc-gh-tjones — APPROVED** [review]

**Review by sfc-gh-mnaides — APPROVED** [review]

**Comment by sfc-gh-mnaides** [comment]
@sfc-gh-tzhang Might want to wait for https://github.com/snowflakedb/snowflake-ingest-java/pull/140

**Comment by sfc-gh-tzhang** [comment]
> @sfc-gh-tzhang Might want to wait for #140

Yes! I totally missed that one as it doesn't show up in the `review requests` tab anymore as long as one person from streaming-ingest reviewed it :(

**Comment by sfc-gh-japatel** [comment]
If we can also include this: https://github.com/snowflakedb/snowflake-ingest-java/pull/144 (Once it is approved)

**Comment by sfc-gh-mnaides** [comment]
@sfc-gh-tzhang Our beta build is missing some important fixes right now, let's go ahead and release this and we can do a second patch shortly once the other PRs are in

**Comment by sfc-gh-tjones** [comment]
> @sfc-gh-tzhang Our beta build is missing some important fixes right now, let's go ahead and release this and we can do a second patch shortly once the other PRs are in

The SAP Connector folks caused some incidents on our side with an older version of the Client SDK, let's bump the version so they can test without generating any incidents.

**Comment by sfc-gh-mnaides** [comment]
Merging after talking to @sfc-gh-tzhang offline

**Pull request merged**
