### PR TITLE
NO-SNOW Specify dependencies in public_pom.xml

### PR DESCRIPTION
**Pull request by sfc-gh-lsembera**

### CODE REVIEW

**Comment by sfc-gh-tzhang** [comment]
This is good for now, for longer term we should come up with a better way to automate this instead of updating it manually

**Review by sfc-gh-japatel — COMMENTED** [review]
What happens to the location of this dependency? Do we need relocation here?

**Review by sfc-gh-xhuang — APPROVED** [review]

**Review by sfc-gh-pbennes — APPROVED** [review]
Ohh yeah I can see how we missed this.

**Comment by sfc-gh-lsembera** [comment]
> What happens to the location of this dependency? Do we need relocation here?

No, these two are not being shaded, they will be declared as transitive dependencies of the SDK in the final pom.xml uploaded to Maven Central.

**Comment by sfc-gh-pbennes** [comment]
> This is good for now, for longer term we should come up with a better way to automate this instead of updating it manually

The maven-shade-plugin supports this, but the other way around. Usually jars are unshaded by default and then when shading the maven-shade-plugin will produce a separate dependency-reduced-pom.xml which doesn't include shaded dependencies in the dependencies section of the published pom.xml.

If we move to that model and align with the maven-shade-plugin that will make managing both regular and shaded jars easier to maintain I think.

**Pull request merged**
