### PR TITLE
SNOW-667402:Semgrep workflow update

### PR DESCRIPTION
**Pull request by sfc-gh-hpathak**
This PR removes legacy semgrep workflows for a reusable workflow. Local semgrep rules have been deleted. If your repo had a semgrep stage in the Jenkinsfile, we attempted to delete it. Please review changes and merge them as soon as possible.
[Announcement](https://snowflake.slack.com/archives/C02BTC3HY/p1661797484408489)

### CODE REVIEW

**Review by sfc-gh-tzhang — APPROVED** [review]
LGTM, thanks!

**Comment by sfc-gh-hpathak** [comment]
@sfc-gh-tzhang Thats the old workflow, GH has some issue like this when that file gets updated. are you admin on the repo? If so could you disable the old workflow name "semgrep" as "required"

**Comment by sfc-gh-tzhang** [comment]
@sfc-gh-hpathak Looks like there're three of them (semgrep.yml, semgrep_internal.yml), should I disable all of them?

**Comment by sfc-gh-hpathak** [comment]
@sfc-gh-tzhang Yes, once this PR is merged, there will be a new one "run semgrep checks" which we should mark as required. Rest all should be deleted.

**Pull request merged**
