### PR TITLE
Mark getLatestCommittedOffsetToken as Nullable

### PR DESCRIPTION
**Pull request by jdcaperon**
Thoughts? Would help with being careful about null values.

### CODE REVIEW

**Review by sfc-gh-tzhang — APPROVED** [review]

**Comment by sfc-gh-tzhang** [comment]
@sfc-gh-rcheng any idea about the current process for PRs from outside?

**Comment by sfc-gh-rcheng** [comment]
@jdcaperon since you are a first time contributor, you'll need to sign our CLA. What is a good email to send this to?

**Comment by jdcaperon** [comment]
@sfc-gh-rcheng please send this to `jack@canva.com` cheers!

**Comment by jdcaperon** [comment]
Sorry all, I am waiting on Legal to clear this CLA :'(

**Comment by jdcaperon** [comment]
@sfc-gh-rcheng CLA has been approved for all `*@canva.com` :D

**Pull request closed without merging**
