### PR TITLE
Remove CLA bot and update README.md to include cla and formatter requirements

### PR DESCRIPTION
**Pull request by sfc-gh-rcheng**
CLA bot has been flakey, removing that and adding requirements to readme for formatter and cla

### CODE REVIEW

**Review by sfc-gh-xhuang — APPROVED** [review]

**Review by sfc-gh-tzhang — APPROVED** [review]

**Comment by sfc-gh-lsembera** [comment]
@sfc-gh-rcheng Can this one be merged? I am hoping it will solve my failing CLA Assistant merge gates.

**Review by sfc-gh-lsembera — APPROVED** [review]

**Comment by sfc-gh-rcheng** [comment]
@sfc-gh-lsembera Unfortunately this fix didn't fix the CLA bot for [KC](https://github.com/snowflakedb/snowflake-kafka-connector/actions/runs/5128912188). I've followed up with Mark but we haven't been able to root cause the issue. We may need to remove the CLA bot if it is flakey.

CLA bot isn't required for merging, you can ignore the errors for now, if you need to merge your PR.

**Review by sfc-gh-xhuang — APPROVED** [review]

**Comment by sfc-gh-tzhang** [comment]
@sfc-gh-rcheng Do you plan to add the bot back later?

**Review by sfc-gh-tzhang — APPROVED** [review]

**Comment by sfc-gh-tzhang** [comment]
And looks like there is a Snowpipe test failure, could you create a JIRA and assign to the Snowpipe folks to take a look?

**Comment by sfc-gh-rcheng** [comment]
@sfc-gh-tzhang Currently I don't plan on adding the bot back. In its current state it is too flakey and doesn't leave a great impression on external contributors. If we have a lot of external PRs, we can follow up with legal or others to find an alternative to the CLA bot.

**Comment by sfc-gh-rcheng** [comment]
Created JIRA: https://snowflakecomputing.atlassian.net/browse/SNOW-837787

**Pull request merged**
