### PR TITLE
Adds back provided scope for slf4j-api

### PR DESCRIPTION
**Pull request by sfc-gh-tjones**

### CODE REVIEW

**Review by sfc-gh-japatel — APPROVED** [review]
lgtm!

**Review by sfc-gh-tzhang — APPROVED** [review]

**Comment by sfc-gh-tzhang** [comment]
@sfc-gh-tjones I just updated the branch, do you want to sign the CLA and merge the change once it passes the gate?

**Comment by sfc-gh-tjones** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sfc-gh-tzhang** [comment]
@sfc-gh-rcheng Any idea about the CLA check failure?

**Pull request merged**
