### PR TITLE
SNOW-1707031 hadoop upgrade for vulnerability fix

### PR DESCRIPTION
**Pull request by sfc-gh-japatel**
[SNOW-1707031](https://snowflakecomputing.atlassian.net/browse/SNOW-1707031)

Added few exclusions. Here is how I did it: I looked at the failed command of `mvn clean install` and compared it with `mvn dependency:tree`

Mostly it's about finding which dependencies can be excluded so that the new upgrade which brought in new dependencies are used. 

Other minor fixes for merge gates to pass. Ran locally and it succeeeded
```
mvn install -PcheckShadedContent -DskipTests=true --batch-mode --show-version
```

[SNOW-1707031]: https://snowflakecomputing.atlassian.net/browse/SNOW-1707031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by sfc-gh-xhuang — APPROVED** [review]
Thanks for fixing this!

**Review by sfc-gh-tzhang — APPROVED** [review]
LGTM, @sfc-gh-lsembera do we need to check with security about the added license?

**Comment by sfc-gh-japatel** [comment]
> LGTM, @sfc-gh-lsembera do we need to check with security about the added license?

I dont think so, it's existing license we are adding and it's a known one.

**Comment by sfc-gh-lsembera** [comment]
Thanks, @sfc-gh-japatel. The only issue I see here is that it will further inflate the JAR size. Should we try to exclude the new dependencies and see whether tests pass? I don't see why would we the SDK need netty.

**Pull request merged**
